version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db1:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: kirill196/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: kirill196/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: kirill196/kittygram_gateway
    depends_on:
      - backend
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media